### ISSUE TITLE
Error on repository init with PostgreSQL 10

### ISSUE THREAD

**Issue by mbabic84** [locationtech/geogig#417]
When i try to init new repository in postgresql database i got this error

**Expected version format x.y.z, got 10.3 (Debian 10.3-1.pgdg90+1)**

I try to init with this command:
`geogig --repo "postgresql://sandbox-postgis/geogig/public/main?user=postgres&password=******" init`

**Comment by emerkle826** [comment]
@mbabic84 That bug was fixed recently, but it is not yet in an official release. If you pull the latest `master` or `1.2.x` branches and rebuild GeoGig, it will work with PostgreSQL 10.

**Comment by mbabic84** [comment]
Hello,

thank you for replay. I just try to use latest master and 1.2.x and problem is still there.

`Expected version format x.y.z or x.y, got 10.3 (Ubuntu 10.3-1.pgdg16.04+1)`

`         Project Version : 1.3-SNAPSHOT
              Build Time : April 18, 2018 at 12:41:05 UTC
         Build User Name : 
        Build User Email : 
              Git Branch : master
           Git Commit ID : 58bdc83b263b84efd0b16154011a856a235bdd7f
         Git Commit Time : April 18, 2018 at 00:22:12 UTC
  Git Commit Author Name : Gabriel Roldan
 Git Commit Author Email : gabriel.roldan@gmail.com
      Git Commit Message : Merge pull request #424 from groldan/feature/diff_feature_source`

**Comment by emerkle826** [comment]
@mbabic84 it would seem that the PostgreSQL version you have installed reports more than just a version number when `show server_version` is executed against the database.  Sorry I missed that originally (the instances I tested returned only `10.3`, not `10.3 (Debian 10.3-1.pgdg90+1)`. Let me see if I can come up with a better fix.

**Comment by emerkle826** [comment]
@mbabic84 I just put up this PR: https://github.com/locationtech/geogig/pull/425. That should finally address your issue. Sorry I ddin't see it sooner.
Once the PR is merged in `master` I'll get it backported to `1.2.x` as well.

**Comment by emerkle826** [comment]
@mbabic84 The PRs have been merged. This issue should be resolved now (`master` and `1.2.x`).

**Comment by mbabic84** [comment]
Yes, I can confirm that. Now it works. Thank You
